cs-24-sw-8-04/scheduling

backend/Cargo.lock
backend/Cargo.toml
backend/src/data_model.rs
backend/src/data_model/account.rs
backend/src/data_model/device.rs
backend/src/data_model/event.rs
backend/src/data_model/task.rs
backend/src/data_model/time.rs
backend/src/extractors/auth.rs
backend/src/handlers/accounts.rs
backend/src/handlers/devices.rs
backend/src/handlers/tasks.rs
backend/src/main.rs
backend/src/protocol/devices.rs
backend/src/protocol/tasks.rs

Ids are now typed to avoid type confusion

backend: Use newtypes for ids

---

.github/workflows/frontend.yml

Emulator brokey

---

backend/src/data_model/device.rs
backend/src/data_model/task.rs
backend/src/handlers/devices.rs
backend/src/handlers/tasks.rs
backend/src/main.rs
frontend/app/src/main/java/dk/scheduling/schedulingfrontend/api/ApiService.kt
frontend/app/src/main/java/dk/scheduling/schedulingfrontend/api/protocol/Devices.kt
frontend/app/src/main/java/dk/scheduling/schedulingfrontend/api/protocol/Tasks.kt
frontend/app/src/test/java/dk/scheduling/schedulingfrontend/ApiServiceTest.kt

Created tasks and device endpoints including tests for it for the back end and front end

Device and tasks

---

frontend/app/src/main/java/dk/scheduling/schedulingfrontend/HomePage.kt
frontend/app/src/main/java/dk/scheduling/schedulingfrontend/MainLayout.kt
frontend/app/src/main/java/dk/scheduling/schedulingfrontend/Pages.kt

Use ElevatedCard for the device cards.
Fix issue where left and right parts of the card's shadow is cut off.
Clean up the DeviceCard to not use spacers.
Move the delete button into the expanded area in the lower right corner.
Animate the expansion and contraction of the card.
Use a scaffold as the root node of the app.
This provides the bottom bar, background color and other niceties.
Change pagesInfo list to a map.

Fix small issues

---

backend/Cargo.lock
backend/Cargo.toml
backend/src/data_model.rs
backend/src/data_model/graph.rs
backend/src/scheduling.rs
backend/src/scheduling/scheduler.rs
backend/src/scheduling/unpub_event.rs
backend/src/scheduling/unpublished_event.rs
protocol/src/time.rs

resolves #12.
Made an implementation for the naïve scheduling algorithm, also created the needed data types which the algorithm is dependent upon.

Naive scheduling

---

backend/src/scheduling/scheduler.rs
protocol/src/devices.rs
protocol/src/tasks.rs

Made macro for creating the expected result and a factory for creating tasks for the tests

Started working on a test suite for testing the current and coming scheduling algorithms

---

frontend/app/src/main/java/dk/scheduling/schedulingfrontend/components/DateRangePicker.kt
frontend/app/src/test/java/dk/scheduling/schedulingfrontend/DateRangeTest.kt

Now using better built-in datatypes.
SQUASH THIS BRANCH.

Create task data structure

---

frontend/app/src/main/java/dk/scheduling/schedulingfrontend/api/protocol/Devices.kt
frontend/app/src/main/java/dk/scheduling/schedulingfrontend/api/protocol/Tasks.kt

Added comments to api data types in the frontend with their units to avoid confusion

Add comments with units to frontend API data types

---

backend/Cargo.lock
backend/Cargo.toml
backend/src/data_model/graph.rs
backend/src/scheduling/background_service.rs
backend/src/scheduling/scheduler.rs
backend/src/scheduling/task_for_scheduler.rs
frontend/app/src/main/java/dk/scheduling/schedulingfrontend/api/protocol/Devices.kt
frontend/app/src/main/java/dk/scheduling/schedulingfrontend/api/protocol/Tasks.kt
protocol/src/time.rs

Added a scheduling algorithm based on the current global scheduling to create the best schedule for all possible permutations of tasks as input to the global algorithm.

Add "All Permutations Algorithm"

---

backend/src/scheduling/scheduler.rs

Changed the naive scheduler to modify the input graph so that we can evaluate the naive vs. other schedulers

 Changed naive scheduler to ease comparison between the algorithms

---

frontend/app/src/main/java/dk/scheduling/schedulingfrontend/components/Loading.kt

Created a loading component. it will be used in device overview page and task overview page in a later pull request.

Loading indicator component

---

backend/src/scheduling/background_service.rs

Tasks that cannot be scheduled (end time is less than now) or the duration is too big for end time - now.

Filter Tasks based on their datetime interval

---

frontend/app/src/main/java/dk/scheduling/schedulingfrontend/repositories/device/DeviceRepository.kt
frontend/app/src/main/java/dk/scheduling/schedulingfrontend/repositories/device/IDeviceRepository.kt
frontend/app/src/main/java/dk/scheduling/schedulingfrontend/repositories/task/ITaskRepository.kt
frontend/app/src/main/java/dk/scheduling/schedulingfrontend/repositories/task/TaskRepository.kt
frontend/app/src/main/java/testdata/DummyDeviceRepository.kt
frontend/app/src/main/java/testdata/DummyTaskRepository.kt

Interface for TaskRepository and DeviceRepository.
Dummy implementations of both interfaces.

App, interface for Device and Task repos

---

frontend/app/src/main/java/dk/scheduling/schedulingfrontend/components/Loading.kt

This PR place the Loading indicator in center

Loading indicator centered

---

frontend/app/src/main/java/dk/scheduling/schedulingfrontend/MainActivity.kt
frontend/app/src/main/java/dk/scheduling/schedulingfrontend/repositories/event/EventRepository.kt
frontend/app/src/main/java/dk/scheduling/schedulingfrontend/repositories/event/IEventRepository.kt
frontend/app/src/main/java/dk/scheduling/schedulingfrontend/repositories/overviews/OverviewRepository.kt
frontend/app/src/main/java/testdata/DummyDeviceRepository.kt
frontend/app/src/main/java/testdata/DummyEventRepository.kt
frontend/app/src/main/java/testdata/DummyTaskRepository.kt

In this PR the following has happen:
- Created an Event repository interface.
- Changed the Overview repository to take other types of arguments.
- Added repositories to the main activity, such that they can be used in the pages.

1. App - created an event repository - add to repositories to main activity

---

frontend/app/src/main/java/dk/scheduling/schedulingfrontend/pages/HomePage.kt
frontend/app/src/main/java/dk/scheduling/schedulingfrontend/pages/TaskOverviewPage.kt

This PR adds loading component to the device and task overview pages, such that if the networks delay it will show a loading bar

2. APP - Add loading screen to device and task overview pages

---

frontend/app/src/main/java/dk/scheduling/schedulingfrontend/MainActivity.kt
frontend/app/src/main/java/dk/scheduling/schedulingfrontend/pages/CreateDevicePage.kt
frontend/app/src/main/java/dk/scheduling/schedulingfrontend/pages/HomePage.kt
frontend/app/src/main/java/dk/scheduling/schedulingfrontend/pages/TaskOverviewPage.kt
frontend/app/src/main/java/testdata/DummyDeviceRepository.kt

This PR links device and task overview and create device pages with the repositories.

3. Connect pages with repository expect create task page

---

backend/src/handlers/events.rs
backend/src/main.rs

Added the functionality such that we dont get all history of events, only the ones planed in the future and those active right now.

Updated event endpoint

---

frontend/app/src/main/java/dk/scheduling/schedulingfrontend/components/DateRangePicker.kt
frontend/app/src/main/java/dk/scheduling/schedulingfrontend/components/Loading.kt
frontend/app/src/main/java/dk/scheduling/schedulingfrontend/components/StandardDropDownMenu.kt
frontend/app/src/main/java/dk/scheduling/schedulingfrontend/components/TimePicker.kt
frontend/app/src/main/java/dk/scheduling/schedulingfrontend/model/Duration.kt
frontend/app/src/main/java/dk/scheduling/schedulingfrontend/pages/CreateTaskPage.kt

Minor improvements, such as oneline-functions, value setters

Frontend minor mending

---

frontend/app/src/main/java/dk/scheduling/schedulingfrontend/api/ApiClient.kt
frontend/app/src/main/java/dk/scheduling/schedulingfrontend/api/protocol/Devices.kt
frontend/app/src/main/java/dk/scheduling/schedulingfrontend/components/Dateformat.kt
frontend/app/src/main/java/dk/scheduling/schedulingfrontend/pages/SignUpPage.kt

- Remove unused code
- Added explicit datatypes where necessary

Frontend improvements

---

frontend/app/src/main/java/dk/scheduling/schedulingfrontend/components/StandardDropDownMenu.kt
frontend/app/src/main/java/dk/scheduling/schedulingfrontend/model/TaskForm.kt
frontend/app/src/main/java/dk/scheduling/schedulingfrontend/pages/CreateTaskPage.kt
frontend/app/src/test/java/dk/scheduling/schedulingfrontend/TaskFormTest.kt

Closes #136
Defaults to unselected:
If no device present:

TaskForm device id now nullable

---

frontend/app/src/main/AndroidManifest.xml
frontend/app/src/main/java/dk/scheduling/schedulingfrontend/App.kt
frontend/app/src/main/java/dk/scheduling/schedulingfrontend/MainActivity.kt
frontend/app/src/main/java/dk/scheduling/schedulingfrontend/module/AppModule.kt

Use repo as Dependency injection, this is required when making push notification

2. Dependency injection

---

protocol/src/devices.rs

You shouldn't modify device ids >:(

Remove add assign trait for DeviceId

---

frontend/build.gradle.kts
frontend/gradle/wrapper/gradle-wrapper.properties

Bump com.android.application from 8.3.2 to 8.4.0 in /frontend

Update gradle to 8.6

---

frontend/app/src/main/java/dk/scheduling/schedulingfrontend/model/TaskForm.kt

The dateRange.rangeStart() and dateRange.rangeEnd() give the correct date but the time is from 02:00 and not 00:00. When adding the date time will always be 2 hours more than it should. So this PR fixes the problem of invalid time

Fix time in task form

---

frontend/app/src/main/java/dk/scheduling/schedulingfrontend/components/Dateformat.kt

Remove AM and PM and use 24-time

New date time formatter

---

.gitignore
frontend/app/build.gradle.kts
frontend/app/schemas/dk.scheduling.schedulingfrontend.database.EventDatabase/1.json
frontend/app/src/androidTest/java/dk/scheduling/schedulingfrontend/EventWorkerTest.kt
frontend/app/src/main/AndroidManifest.xml
frontend/app/src/main/java/dk/scheduling/schedulingfrontend/App.kt
frontend/app/src/main/java/dk/scheduling/schedulingfrontend/background/EventAlarmSetterWorker.kt
frontend/app/src/main/java/dk/scheduling/schedulingfrontend/eventnotification/EventAlarm.kt
frontend/app/src/main/java/dk/scheduling/schedulingfrontend/eventnotification/EventAlarmDao.kt
frontend/app/src/main/java/dk/scheduling/schedulingfrontend/eventnotification/EventAlarmReceiver.kt
frontend/app/src/main/java/dk/scheduling/schedulingfrontend/eventnotification/EventDatabase.kt
frontend/app/src/main/java/dk/scheduling/schedulingfrontend/eventnotification/EventNotifyScheduler.kt
frontend/app/src/main/java/dk/scheduling/schedulingfrontend/module/AppModule.kt
frontend/app/src/main/java/dk/scheduling/schedulingfrontend/repositories/event/EventRepository.kt
frontend/app/src/main/java/testdata/DummyDeviceRepository.kt
frontend/app/src/main/res/values/strings.xml

This PR enables push notification.
Use Room Database to keep track of alarms.
To see the notification the user first has to enable notification for our application in Settings on the device.
Missing: A way to request permission to show notification.

3. Push notification

---

README.md

Simulator is missing, but Mads can do that :upside_down_face:

Add text to README.md

---

.github/workflows/backend.yml
backend/Cargo.lock
backend/Cargo.toml
backend/benches/benchmark.rs
backend/make_new_db.sh
backend/src/data_model.rs
backend/src/handlers/tasks.rs
backend/src/main.rs
backend/src/scheduling/background_service.rs
backend/src/scheduling/scheduler.rs
frontend/app/src/main/java/dk/scheduling/schedulingfrontend/pages/SignUpPage.kt
protocol/Cargo.lock
protocol/Cargo.toml
protocol/src/graph.rs
protocol/src/lib.rs
protocol/src/scheduling.rs
protocol/src/tasks.rs
simulator/Cargo.lock
simulator/src/compare_algorithms.rs
simulator/src/data_factory.rs
simulator/src/lib.rs
simulator/src/main.rs

We can simulate the scheduling of tasks, and compare the naive and global algorithm with the simulation

Simulation of task scheduling

---

README.md
backend/benches/benchmark.rs
backend/make_new_db.bat
backend/src/main.rs
backend/src/scheduling/scheduler.rs
simulator/src/compare_algorithms.rs

All permutation simulation has been added along with a readme on how to simulate

All permutation simulation

---

frontend/app/src/main/java/dk/scheduling/schedulingfrontend/pages/LoginPage.kt

Add documentation to login page guide code

Add documentation

---

frontend/app/src/main/java/dk/scheduling/schedulingfrontend/model/TaskForm.kt
frontend/app/src/main/java/dk/scheduling/schedulingfrontend/pages/CreateDevicePage.kt
frontend/app/src/main/java/dk/scheduling/schedulingfrontend/pages/LoginPage.kt
frontend/app/src/main/java/dk/scheduling/schedulingfrontend/pages/SignUpPage.kt

Adding further validation

---

frontend/app/src/androidTest/java/dk/scheduling/schedulingfrontend/EventWorkerTest.kt
frontend/app/src/main/AndroidManifest.xml
frontend/app/src/main/java/dk/scheduling/schedulingfrontend/App.kt
frontend/app/src/main/java/dk/scheduling/schedulingfrontend/background/eventnotification/EventAlarmReceiver.kt
frontend/app/src/main/java/dk/scheduling/schedulingfrontend/background/eventnotification/EventAlarmSetterWorker.kt
frontend/app/src/main/java/dk/scheduling/schedulingfrontend/background/eventnotification/EventNotifyScheduler.kt
frontend/app/src/main/java/dk/scheduling/schedulingfrontend/datasources/eventalarm/EventAlarm.kt
frontend/app/src/main/java/dk/scheduling/schedulingfrontend/datasources/eventalarm/EventAlarmDao.kt
frontend/app/src/main/java/dk/scheduling/schedulingfrontend/datasources/eventalarm/EventDatabase.kt
frontend/app/src/main/java/dk/scheduling/schedulingfrontend/repositories/event/EventRepository.kt

Need a small change in the structure to follow the same as the implementation report

Update folder structure

---

frontend/app/src/main/java/dk/scheduling/schedulingfrontend/gui/components/Dateformat.kt
frontend/app/src/main/java/dk/scheduling/schedulingfrontend/gui/components/Refreshable.kt
frontend/app/src/main/java/dk/scheduling/schedulingfrontend/gui/pages/AccountPage.kt
frontend/app/src/main/java/dk/scheduling/schedulingfrontend/gui/pages/CreateDevicePage.kt
frontend/app/src/main/java/dk/scheduling/schedulingfrontend/gui/pages/HomePage.kt
frontend/app/src/main/java/dk/scheduling/schedulingfrontend/gui/pages/TaskOverviewPage.kt

Refactor refreshable as a component

Refactor refreshable as a component
